# config.yml
backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)
site_url: https://kentcommunityhousinghub.org
media_folder: '/src/uploads'
logo_url: https://kentcommunityhousinghub.org/assets/images/meta.jpg
public_folder: '/uploads'
collections:
    - name: site
      label: Site
      delete: false
      editor:
          preview: false
      files:
          - file: src/data/meta.json
            label: Meta
            name: meta
            fields:
                - label: Title
                  name: title
                  required: true
                  widget: string
                  hint: ''
                  default: ''
                - label: Description
                  name: description
                  required: true
                  widget: text
                  hint: ''
                  default: ''
                - label: URL
                  name: url
                  required: true
                  widget: string
                  hint: ''
                  default: ''
                - label: Image
                  name: image
                  required: true
                  widget: image
                  hint: ''
                  default: ''
                  allow_multiple: true
                - label: Facebook
                  name: facebook
                  required: false
                  widget: string
                  hint: ''
                  default: ''
                - label: Twitter
                  name: twitter
                  required: false
                  widget: string
                  hint: ''
                  default: ''
                - label: Instagram
                  name: instagram
                  required: false
                  widget: string
                  hint: ''
                  default: ''
          - file: src/data/contact.json
            label: Contact details
            name: contact
            fields:
                - label: Contact name
                  name: name
                  required: false
                  widget: string
                  hint: ''
                  default: ''
                - label: Contact email
                  name: email
                  required: false
                  widget: string
                  hint: ''
                  default: ''
                - label: Phone (main)
                  name: phone_main
                  required: false
                  widget: string
                  hint: ''
                  default: ''
                - label: Phone (mobile)
                  name: phone_mobile
                  required: false
                  widget: string
                  hint: ''
                  default: ''
                - label: Address
                  name: address
                  required: false
                  widget: text
                  hint: ''
                  default: ''
          - file: src/data/home.json
            label: Home
            name: home
            fields:
                - label: Hero – title
                  name: hero_title
                  required: true
                  widget: string
                  hint: ''
                  default: ''
                - label: Hero – description
                  name: hero_description
                  required: true
                  widget: text
                  hint: ''
                  default: ''
                - label: Hero – button text
                  name: hero_button_text
                  required: false
                  widget: string
                  hint: ''
                  default: ''
                - label: Hero – button link
                  name: hero_button_link
                  required: true
                  widget: string
                  hint: Can be an absolute or relative link
                  default: ''
                - label: What We Do – title
                  name: whatwedo_title
                  required: true
                  widget: string
                  hint: ''
                  default: ''
                - label: What We Do – description
                  name: whatwedo_description
                  required: true
                  widget: text
                  hint: ''
                  default: ''
                - label: Community-led Housing – title
                  name: clh_title
                  required: true
                  widget: string
                  hint: ''
                  default: ''
                - label: Community-led Housing – description
                  name: clh_description
                  required: true
                  widget: text
                  hint: ''
                  default: ''
                - label: News – title
                  name: news_title
                  required: true
                  widget: string
                  hint: ''
                  default: ''
                - label: Signup – title
                  name: signup_title
                  required: true
                  widget: string
                  hint: ''
                  default: ''
                - label: Signup – description
                  name: signup_description
                  required: true
                  widget: text
                  hint: ''
                  default: ''
    - name: 'groups'
      label: 'Groups'
      folder: 'src/groups'
      create: true
      editor:
          preview: false
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Link', name: 'link', widget: 'string', required: false }
          - {
                label: 'Facebook',
                name: 'facebook',
                widget: 'string',
                required: false
            }
          - {
                label: 'Twitter',
                name: 'twitter',
                widget: 'string',
                required: false
            }
    - name: 'events'
      label: 'Events'
      folder: 'src/events'
      create: true
      editor:
          preview: false
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
                label: 'Date',
                name: 'date',
                widget: 'datetime',
                time_format: false
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - {
                label: 'Booking link',
                name: 'booking_link',
                widget: 'string',
                hint: 'Enter full URL including the preceding https://...',
                required: false
            }
          - {
                label: 'YouTube embed code',
                name: 'youtube',
                widget: 'text',
                hint: 'Click the "share" button on YouTube then "embed code".',
                required: false
            }
    - name: 'pages'
      label: 'Pages'
      folder: 'src/pages'
      preview_path: '{{slug}}'
      create: true
      editor:
          preview: true
      fields:
          - { name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
          - { label: 'Introduction', name: 'intro', widget: 'text' }
          - {
                label: 'Icon',
                name: 'icon',
                widget: 'select',
                options: ['1', '2', '3', '4', '5']
            }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Navigation'
            name: 'eleventyNavigation'
            widget: 'object'
            fields:
                - {
                      label: 'Label',
                      name: 'key',
                      widget: 'string',
                      required: false
                  }
    - name: 'posts'
      label: 'Blog'
      folder: 'src/posts'
      preview_path: posts/{{slug}}
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
      summary: '{{title}}  ({{day}}.{{month}}.{{year}})'
      editor:
          preview: true
      fields:
          - { name: 'layout', widget: 'hidden', default: 'post' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
                label: 'Image',
                name: 'icon',
                widget: 'select',
                options: ['environment', 'house', 'houses', 'job']
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
