# config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
site_url: https://kentcommunityhousinghub.org
media_folder: '/src/uploads'
logo_url: https://kentcommunityhousinghub.org/assets/images/meta.jpg
public_folder: "/uploads"
collections:
  - name: 'posts'
    label: 'Blog'
    folder: 'src/posts'
    preview_path: posts/{{slug}}
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    summary: "{{title}}  ({{day}}.{{month}}.{{year}})"
    editor:
      preview: true
    fields:
      - { name: 'layout', widget: 'hidden', default: 'layouts/post.njk' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime', dateFormat: 'Do MMM YYYY', timeFormat: false }
      - { label: 'Image', name: 'icon', widget: 'select', options: ['environment','house','houses','job'] }
      - { label: 'Description', name: 'body', widget: 'markdown'}
  - name: 'pages'
    label: 'Pages'
    folder: 'src/pages'
    preview_path: pages/{{slug}}
    create: true
    editor:
      preview: true
    fields:
      - { name: 'layout', widget: 'hidden', default: 'layouts/page.njk' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - { label: 'Introduction', name: 'intro', widget: 'text' }
      - { label: 'Description', name: 'body', widget: 'markdown'}
  - name: site
    label: Site
    delete: false
    editor:
      preview: false
    files:
      - file: src/data/meta.md
        label: Meta
        name: meta
        fields:
          - label: Title
            name: title
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Description
            name: description
            required: true
            widget: text
            hint: ""
            default: ""
          - label: URL
            name: url
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Image
            name: image
            required: true
            widget: image
            hint: ""
            default: ""
            allow_multiple: true
          - label: Facebook
            name: facebook
            required: false
            widget: string
            hint: ""
            default: ""
          - label: Twitter
            name: twitter
            required: false
            widget: string
            hint: ""
            default: ""
          - label: Instagram
            name: instagram
            required: false
            widget: string
            hint: ""
            default: ""
      - file: src/data/contact.json
        label: Contact details
        name: contact
        fields:
          - label: Contact name
            name: name
            required: false
            widget: string
            hint: ""
            default: ""
          - label: Contact email
            name: email
            required: false
            widget: string
            hint: ""
            default: ""
          - label: Phone (main)
            name: phone_main
            required: false
            widget: string
            hint: ""
            default: ""
          - label: Phone (mobile)
            name: phone_mobile
            required: false
            widget: string
            hint: ""
            default: ""
          - label: Address
            name: address
            required: false
            widget: text
            hint: ""
            default: ""
      - file: src/data/home.json
        label: Home
        name: home
        fields:
          - label: Hero – title
            name: hero_title
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Hero – description
            name: hero_description
            required: true
            widget: text
            hint: ""
            default: ""
          - label: Hero – button text
            name: hero_button_text
            required: false
            widget: string
            hint: ""
            default: ""
          - label: Hero – button link
            name: hero_button_link
            required: true
            widget: string
            hint: Can be an absolute or relative link
            default: ""
          - label: What We Do – title
            name: whatwedo_title
            required: true
            widget: string
            hint: ""
            default: ""
          - label: What We Do – description
            name: whatwedo_description
            required: true
            widget: text
            hint: ""
            default: ""
          - label: Community-led Housing – title
            name: clh_title
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Community-led Housing – description
            name: clh_description
            required: true
            widget: text
            hint: ""
            default: ""
          - label: News – title
            name: news_title
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Signup – title
            name: signup_title
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Signup – description
            name: signup_description
            required: true
            widget: text
            hint: ""
            default: ""