# .github/workflows/main.yml

name: Trigger Netlify Build
on:
    schedule:
        # Run at 0015 daily
        - cron: '15 0 * * *'
jobs:
    build:
        name: Request Netlify Webhook
        runs-on: ubuntu-latest
        steps:
            - name: Curl request
              run: curl -X POST -d {} https://api.netlify.com/build_hooks/62042a900d1687272464b5cc
